"""Background music library and rendering services."""

from .library import (
    MIXKIT_CATALOG_URL,
    MIXKIT_LICENSE_NAME,
    MIXKIT_LICENSE_URL,
    ImportResult,
    MusicLibraryError,
    MusicImportMetadata,
    MusicLibraryService,
    default_downloads_folder,
)
from .catalog import (
    CCMIXTER_API_URL,
    CCMIXTER_CATALOG_URL,
    CCMIXTER_TERMS_URL,
    CCMixterCatalogService,
    CCMixterTrack,
    CatalogDownloadResult,
    CatalogProgress,
    MusicCatalogError,
)
from .service import (
    MUSIC_CUE_COLUMNS,
    FFmpegMusicRenderer,
    MusicCue,
    MusicDNAService,
    MusicDNAPlan,
    MusicProgress,
    MusicWorkflowError,
    MusicWorkflowResult,
    MusicWorkflowService,
    format_music_timestamp,
    music_analysis_path,
    music_recommendations_path,
    parse_and_validate_music_cues,
    parse_music_timestamp,
    write_music_csv,
)

__all__ = [
    "MIXKIT_CATALOG_URL",
    "MIXKIT_LICENSE_NAME",
    "MIXKIT_LICENSE_URL",
    "ImportResult",
    "MusicLibraryError",
    "MusicImportMetadata",
    "MusicLibraryService",
    "default_downloads_folder",
    "CCMIXTER_API_URL",
    "CCMIXTER_CATALOG_URL",
    "CCMIXTER_TERMS_URL",
    "CCMixterCatalogService",
    "CCMixterTrack",
    "CatalogDownloadResult",
    "CatalogProgress",
    "MusicCatalogError",
    "MUSIC_CUE_COLUMNS",
    "FFmpegMusicRenderer",
    "MusicCue",
    "MusicDNAService",
    "MusicDNAPlan",
    "MusicProgress",
    "MusicWorkflowError",
    "MusicWorkflowResult",
    "MusicWorkflowService",
    "format_music_timestamp",
    "music_analysis_path",
    "music_recommendations_path",
    "parse_and_validate_music_cues",
    "parse_music_timestamp",
    "write_music_csv",
]
